title: Kelly
description: Kelly的个人博客
author: Kelly
logo: /kelly-zkl.github.io/static/img/avatar.png
github: https://github.com/kelly-zkl
about: Freelance developer

baseurl: "https://kelly-zkl.github.io"
url: "https://kelly-zkl.github.io"

allowsearch: true

disqus_shortname: aboutashu
#google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
